// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function DeleteAll() {
  return window['go']['main']['App']['DeleteAll']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function Toggle(arg1) {
  return window['go']['main']['App']['Toggle'](arg1);
}
