// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1:string):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function DeleteAll():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function List():Promise<Array<Record<string, any>>>;

export function Toggle(arg1:number):Promise<void>;
